defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.4.1-stretch-browsers

version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # build
      - run: yarn run build-prod

      # share build files with subsequent jobs
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./

      # deploy
      - run:
          name: install aws-cli
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awscli
            aws --version
      - run:
          name: sync to s3
          command: |
            aws s3 sync build s3://<REPLACE_ME>/ --delete --acl public-read
            aws s3 cp build/index.html s3://<REPLACE_ME>/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
